support "derived_from" link from input feature "self" href
* restore logging during tests for debugging

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

* update tests to match master branch

[ThreadedStreamConsumer] ERROR org.apache.maven.plugin.surefire.SurefirePlugin - testManifestLevelSentinel2_L1C{LocalDate, Double}[1]  Time elapsed: 0.616 s  <<< ERROR!
java.util.NoSuchElementException: None.get
	at org.openeo.OpenSearchClientTest.testManifestLevelSentinel2(OpenSearchClientTest.scala:444)
	at org.openeo.OpenSearchClientTest.testManifestLevelSentinel2_L1C(OpenSearchClientTest.scala:326)

[ThreadedStreamConsumer] ERROR org.apache.maven.plugin.surefire.SurefirePlugin - testManifestLevelSentinel2_L2A{LocalDate, Double}[1]  Time elapsed: 0.246 s  <<< ERROR!
java.util.NoSuchElementException: None.get
	at org.openeo.OpenSearchClientTest.testManifestLevelSentinel2(OpenSearchClientTest.scala:444)
	at org.openeo.OpenSearchClientTest.testManifestLevelSentinel2_L2A(OpenSearchClientTest.scala:370)

* propagate URL to input feature for OSCARS

https://github.com/Open-EO/openeo-geopyspark-driver/issues/1278

* propagate URL to input feature for CDSE

https://github.com/Open-EO/openeo-geopyspark-driver/issues/1278

* support propagating URL to input feature for load_stac

Also drops the parentheses on FeatureBuilder::build because it has no side effects.

https://github.com/Open-EO/openeo-geopyspark-driver/issues/1278

* support self hrefs without scheme i.e. files on disk

openeo_driver.testing.ApiException: Expected response with status code 200 but got 500. Error: {'code': 'Internal', 'id': 'r-25102111152541f687c29ffbff1ba8df', 'message': 'load_stac: Error when constructing datacube from /var/lib/jenkins/workspace/openeo-geopyspark-driver_PR-1330/tests/data/binary/load_stac/spatiotemporal_netcdf/collection.json: An error occurred while calling o36657.withSelfUrl.\n: java.net.MalformedURLException: no protocol: /var/lib/jenkins/workspace/openeo-geopyspark-driver_PR-1330/tests/data/binary/load_stac/spatiotemporal_netcdf/j-2402271caa2647f79d54a51caddf1388_openEO_0.nc.json\n\tat java.base/java.net.URL.<init>(URL.java:645)\n\tat java.base/java.net.URL.<init>(URL.java:541)\n\tat java.base/java.net.URL.<init>(URL.java:488)\n\tat org.openeo.opensearch.OpenSearchResponses$FeatureBuilder.withSelfUrl(OpenSearchResponses.scala:145)\n\tat jdk.internal.reflect.GeneratedMethodAccessor418.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)\n\tat py4j.ClientServerConnection.run(ClientServerConnection.java:106)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n'}

https://github.com/Open-EO/openeo-geopyspark-driver/issues/1278

* breaking change wrt/ OpenSearchResponses.FeatureBuilder#build

https://github.com/Open-EO/openeo-geopyspark-driver/issues/1278